Update new file names in windows installer.

diff --git a/windows/wincoot-autobuild-all b/windows/wincoot-autobuild-all
--- a/windows/wincoot-autobuild-all
+++ b/windows/wincoot-autobuild-all
@@ -204,33 +204,135 @@ if [ $make_installer_only == 0 ] ; then
       echo waiting for build       > $PUBLIC_HTML_LOGS/gtk2-test-status
       echo BUILDING:: python WinCoot
 
-    if [ "$coot_version_status" = "1" ] ; then
-       echo 'python and python+guile build differ => build again'
-       build_cycle=$(($build_cycle+1))
-       echo tried $build_cycle times so far
-       if [ "$build_cycle" = "3" ] ; then
-  		echo We tried 3 times to build consistent python and python+guile version
-  		echo BUT FAILED!!
-		echo exiting build!
-		build_installer=1
-        	coot_version_status=0
-       fi
-    fi
-   fi 
-  else
-    # coot python did not build ok! We try 3 more times
-    echo python build failed '=>' try again
-    minor_build_cycle=$(($minor_build_cycle+1))
-    echo tried $minor_build_cycle times so far
-    if [ "$minor_build_cycle" = "3" ] ; then
-      echo We tried 3 times to build python coot
-      echo BUT FAILED!!
-      echo exiting build!
-      build_installer=1
-      coot_version_status=0
-    fi
-  fi
-done
+      # do the build
+      echo Now build with:: run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
+      run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
+      python_build_status=$?
+      echo "python build (and test) status: " $python_build_status
+      copy_logs python
+      # read in variables from install run
+      . ${HOME}/wincoot-installer-variables
+      if [ -z "$build_coot_prerelease" ] ; then
+          build_coot_prerelease=0
+      fi
+      if [ -z "$coot_test_status" ] ; then
+          coot_test_status=1
+      fi
+      # copy to public place too
+      cp ${HOME}/wincoot-installer-variables $PUBLIC_HTML_LOGS/
+
+      # if failed dont bother with a guile build and other settings
+      if [ "$coot_build_status" = "0" ] ; then
+
+          if [ "$build_coot_prerelease" = "0" ] ; then
+              install_top_dir=${HOME}/autobuild/${OS}-${HOST}-gtk2
+          else
+              install_top_dir=${HOME}/autobuild/${OS}-${HOST}-pre-release-gtk2
+          fi
+          COOT_PYTHON_VERSION=$install_top_dir/coot-version
+          if [ $make_guile != 0 ] ; then 
+              COOT_GUILE_VERSION=$install_top_dir-guile/coot-version
+              diff ${COOT_PYTHON_VERSION} ${COOT_GUILE_VERSION} 
+              coot_version_status=$?
+          else
+              coot_version_status=0
+          fi
+
+          if [ "$build_coot_prerelease" = "0" ] ; then
+          # stable release
+              touch /z/make_clean_wincoot_prerelease
+          else
+          # pre-release
+              touch /z/make_clean_wincoot_stable
+          fi
+
+          if [ $make_guile != 0 ] ; then 
+              echo 'waiting for guile build      ' > $PUBLIC_HTML_LOGS/gtk2-test-status
+              echo BUILDING:: python+guile WinCoot
+              # possibly could simplify extra flag, but issue if bails out on guile build
+              extra_flag=
+              if [ "$minor_build_cycle" = "2" ] ; then
+                  extra_flag="clean"
+              fi
+              if [ "$build_coot_prerelease" = "0" ] ; then
+              # stable release
+                  if [ -e /z/make_clean_wincoot_stable-guile ] ; then
+                      extra_flag="veryclean"
+                      rm /z/make_clean_wincoot_stable-guile
+                  fi
+              else
+              # pre-release
+                  if [ -e /z/make_clean_wincoot_prerelease-guile ] ; then
+                      extra_flag="veryclean"
+                      rm /z/make_clean_wincoot_prerelease-guile
+                  fi
+              fi
+              echo Now build with:: run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it guile $extra_flag
+              run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it guile $extra_flag
+
+              copy_logs guile
+              diff ${COOT_PYTHON_VERSION} ${COOT_GUILE_VERSION} 
+              coot_version_status=$?
+
+              if [ "$build_coot_prerelease" = "0" ] ; then
+                  # stable release
+                  touch /z/make_clean_wincoot_prerelease-guile
+              else
+                  # pre-release
+                  touch /z/make_clean_wincoot_stable-guile
+              fi
+
+              if [ "$coot_version_status" = "1" ] ; then
+                  echo 'python and python+guile build differ => build again'
+                  build_cycle=$(($build_cycle+1))
+                  echo tried $build_cycle times so far
+                  if [ "$build_cycle" = "3" ] ; then
+                      echo We tried 3 times to build consistent python and python+guile version
+                      echo BUT FAILED!!
+                      echo exiting build!
+                      build_installer=1
+                      coot_version_status=0
+                  fi
+              fi
+          fi 
+          # end make_guile block
+      else
+          # Coot build was bad
+
+          # coot python did not build ok! We try 3 more times
+          echo python build failed '=>' try again
+          minor_build_cycle=$(($minor_build_cycle+1))
+          echo tried $minor_build_cycle times so far
+
+          # make a clean build of failed 3 times previously (last resort)
+          # shall we reset the counter? not yet
+          extra_flag=
+          if [ "$minor_build_cycle" = "2" ] ; then
+              extra_flag="clean"
+          fi
+          if [ "$build_coot_prerelease" = "0" ] ; then
+              # stable release
+              if [ -e /z/make_clean_wincoot_stable ] ; then
+                  extra_flag="veryclean"
+                  rm /z/make_clean_wincoot_stable
+              fi
+          else
+              # pre-release
+              if [ -e /z/make_clean_wincoot_prerelease ] ; then
+                  extra_flag="veryclean"
+                  rm /z/make_clean_wincoot_prerelease
+              fi
+          fi
+
+          if [ "$minor_build_cycle" = "3" ] ; then
+              echo We tried 3 times to build python coot
+              echo BUT FAILED!!
+              echo exiting build!
+              build_installer=1
+              coot_version_status=0
+          fi
+      fi
+    done
 else
  # this is for installer only
  rm /z/make_installer_only
