Updates for new Windows build system. Allow Windows build without guile.

diff --git a/windows/wincoot-autobuild-all b/windows/wincoot-autobuild-all
--- a/windows/wincoot-autobuild-all
+++ b/windows/wincoot-autobuild-all
@@ -40,6 +40,7 @@ if [ -z "$make_guile" ] ; then
   make_guile=1
 fi
 
+# option to not build guile
 # BL note:: this needs to become more flexible!!!
 make_installer_only=${3:-0}
 if [ -e /z/make_installer_only ] ; then
@@ -50,8 +51,8 @@ if [ -z "$make_installer_only" ] ; then
 fi
 
 #
-BINARY_DIR=/c/MinGW/msys/1.0/home/bernhard/public_html/software/binaries/pre-release
-PRE_BINARY_DIR=/c/MinGW/msys/1.0/home/bernhard/public_html/software/binaries/pre-release
+BINARY_DIR=/c/MinGW/msys/1.0/home/bernhard/public_html/software/binaries/nightlies/pre-release
+PRE_BINARY_DIR=/c/MinGW/msys/1.0/home/bernhard/public_html/software/binaries/nightlies/pre-release
 # test if there is enough disk space first
 (
 fsutil.exe volume diskfree c: > ${HOME}/diskspace.tmp
@@ -79,17 +80,17 @@ function copy_logs {
 
   echo Copy logs from LOCAL to PUBLIC $1
   if [ $1 = "python" ] ; then 
-      # copy log files from local to public html
-      cp -p $LOCAL_HTML_LOGS/gtk2-build.log $PUBLIC_HTML_LOGS/
-      cp -p $LOCAL_HTML_LOGS/gtk2-build.log $PUBLIC_HTML_LOGS/gtk2-python-build.log
-      cp -a $LOCAL_HTML_LOGS/$HOSTLOG_STUB/.  $PUBLIC_HTML_LOGS/
-      cp -p $LOCAL_HTML_LOGS/gtk2-test.log  $PUBLIC_HTML_LOGS/
-      cp -p $LOCAL_HTML_LOGS/gtk2-test.log  $PUBLIC_HTML_LOGS/gtk2-python-test.log
+  # copy log files from local to public html
+   cp -p $LOCAL_HTML_LOGS/gtk2-build.log $PUBLIC_HTML_LOGS/
+   cp -p $LOCAL_HTML_LOGS/gtk2-build.log $PUBLIC_HTML_LOGS/gtk2-python-build.log
+   cp -r -p $LOCAL_HTML_LOGS/$HOSTLOG_STUB/  $PUBLIC_HTML_LOGS/
+   cp -p $LOCAL_HTML_LOGS/gtk2-test.log  $PUBLIC_HTML_LOGS/
+   cp -p $LOCAL_HTML_LOGS/gtk2-test.log  $PUBLIC_HTML_LOGS/gtk2-python-test.log
   else
     # copy log files from local to public html
     if [ $make_guile != 0 ] ; then 
       cp -p $LOCAL_HTML_LOGS/gtk2-guile-build.log $PUBLIC_HTML_LOGS/
-      cp -a $LOCAL_HTML_LOGS/${HOSTLOG_STUB}-guile/.  $PUBLIC_HTML_LOGS/
+      cp -r -p $LOCAL_HTML_LOGS/${HOSTLOG_STUB}-guile/  $PUBLIC_HTML_LOGS/
       cp -p $LOCAL_HTML_LOGS/gtk2-guile-test.log  $PUBLIC_HTML_LOGS/
     fi
   fi
@@ -152,6 +153,49 @@ fi
 
 if [ $make_installer_only == 0 ] ; then
 
+while [ $coot_version_status != 0 ]
+do
+  # build a python version
+  echo writing progress status to public html $PUBLIC_HTML_LOGS
+  echo write to file build-in-progress @`date +"%a_%d_%b_%H:%M"`
+  echo build-in-progress @`date +"%a_%d_%b_%H:%M"`> $PUBLIC_HTML_LOGS/gtk2-build-status
+  echo waiting for build       > $PUBLIC_HTML_LOGS/gtk2-test-status
+  echo BUILDING:: python WinCoot
+  # make a clean build of failed 3 times previously (last resort)
+  # shall we reset the counter? not yet
+  extra_flag=
+  if [ "$minor_build_cycle" = "2" ] ; then
+      extra_flag="clean"
+  fi
+  if [ "$build_coot_prerelease" = "0" ] ; then
+     # stable release
+     if [ -e /z/make_clean_wincoot_stable ] ; then
+        extra_flag="veryclean"
+        rm /z/make_clean_wincoot_stable
+     fi
+  else
+     # pre-release
+     if [ -e /z/make_clean_wincoot_prerelease ] ; then
+        extra_flag="veryclean"
+        rm /z/make_clean_wincoot_prerelease
+     fi
+  fi
+  echo Now build with:: run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
+  run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
+  python_build_status=$?
+  echo python build status $python_build_status
+  copy_logs python
+  # read in variables from install run
+  . ${HOME}/wincoot-installer-variables
+  if [ -z "$build_coot_prerelease" ] ; then
+    build_coot_prerelease=0
+  fi
+  # copy to public place too
+  cp ${HOME}/wincoot-installer-variables $PUBLIC_HTML_LOGS/
+
+
+if [ $make_installer_only == 0 ] ; then
+
     while [ $coot_version_status != 0 ]
       do
       # build a python version
@@ -161,140 +205,38 @@ if [ $make_installer_only == 0 ] ; then
       echo waiting for build       > $PUBLIC_HTML_LOGS/gtk2-test-status
       echo BUILDING:: python WinCoot
 
-      # do the build
-      echo Now build with:: run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
-      run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it $extra_flag
-      python_build_status=$?
-      echo "python build (and test) status: " $python_build_status
-      copy_logs python
-      # read in variables from install run
-      . ${HOME}/wincoot-installer-variables
-      if [ -z "$build_coot_prerelease" ] ; then
-          build_coot_prerelease=0
-      fi
-      if [ -z "$coot_test_status" ] ; then
-          coot_test_status=1
-      fi
-      # copy to public place too
-      cp ${HOME}/wincoot-installer-variables $PUBLIC_HTML_LOGS/
-
-      # if failed dont bother with a guile build and other settings
-      if [ "$coot_build_status" = "0" ] ; then
-
-          if [ "$build_coot_prerelease" = "0" ] ; then
-              install_top_dir=${HOME}/autobuild/${OS}-${HOST}-gtk2
-          else
-              install_top_dir=${HOME}/autobuild/${OS}-${HOST}-pre-release-gtk2
-          fi
-          COOT_PYTHON_VERSION=$install_top_dir/coot-version
-          if [ $make_guile != 0 ] ; then 
-              COOT_GUILE_VERSION=$install_top_dir-guile/coot-version
-              diff ${COOT_PYTHON_VERSION} ${COOT_GUILE_VERSION} 
-              coot_version_status=$?
-          else
-              coot_version_status=0
-          fi
-
-          if [ "$build_coot_prerelease" = "0" ] ; then
-          # stable release
-              touch /z/make_clean_wincoot_prerelease
-          else
-          # pre-release
-              touch /z/make_clean_wincoot_stable
-          fi
-
-          if [ $make_guile != 0 ] ; then 
-              echo 'waiting for guile build      ' > $PUBLIC_HTML_LOGS/gtk2-test-status
-              echo BUILDING:: python+guile WinCoot
-              # possibly could simplify extra flag, but issue if bails out on guile build
-              extra_flag=
-              if [ "$minor_build_cycle" = "2" ] ; then
-                  extra_flag="clean"
-              fi
-              if [ "$build_coot_prerelease" = "0" ] ; then
-              # stable release
-                  if [ -e /z/make_clean_wincoot_stable-guile ] ; then
-                      extra_flag="veryclean"
-                      rm /z/make_clean_wincoot_stable-guile
-                  fi
-              else
-              # pre-release
-                  if [ -e /z/make_clean_wincoot_prerelease-guile ] ; then
-                      extra_flag="veryclean"
-                      rm /z/make_clean_wincoot_prerelease-guile
-                  fi
-              fi
-              echo Now build with:: run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it guile $extra_flag
-              run_tests=true build_coot_prerelease=${build_coot_prerelease} $build_it guile $extra_flag
-
-              copy_logs guile
-              diff ${COOT_PYTHON_VERSION} ${COOT_GUILE_VERSION} 
-              coot_version_status=$?
-
-              if [ "$build_coot_prerelease" = "0" ] ; then
-                  # stable release
-                  touch /z/make_clean_wincoot_prerelease-guile
-              else
-                  # pre-release
-                  touch /z/make_clean_wincoot_stable-guile
-              fi
-
-              if [ "$coot_version_status" = "1" ] ; then
-                  echo 'python and python+guile build differ => build again'
-                  build_cycle=$(($build_cycle+1))
-                  echo tried $build_cycle times so far
-                  if [ "$build_cycle" = "3" ] ; then
-                      echo We tried 3 times to build consistent python and python+guile version
-                      echo BUT FAILED!!
-                      echo exiting build!
-                      build_installer=1
-                      coot_version_status=0
-                  fi
-              fi
-          fi 
-          # end make_guile block
-      else
-          # Coot build was bad
-
-          # coot python did not build ok! We try 3 more times
-          echo python build failed '=>' try again
-          minor_build_cycle=$(($minor_build_cycle+1))
-          echo tried $minor_build_cycle times so far
-
-          # make a clean build of failed 3 times previously (last resort)
-          # shall we reset the counter? not yet
-          extra_flag=
-          if [ "$minor_build_cycle" = "2" ] ; then
-              extra_flag="clean"
-          fi
-          if [ "$build_coot_prerelease" = "0" ] ; then
-              # stable release
-              if [ -e /z/make_clean_wincoot_stable ] ; then
-                  extra_flag="veryclean"
-                  rm /z/make_clean_wincoot_stable
-              fi
-          else
-              # pre-release
-              if [ -e /z/make_clean_wincoot_prerelease ] ; then
-                  extra_flag="veryclean"
-                  rm /z/make_clean_wincoot_prerelease
-              fi
-          fi
-
-          if [ "$minor_build_cycle" = "3" ] ; then
-              echo We tried 3 times to build python coot
-              echo BUT FAILED!!
-              echo exiting build!
-              build_installer=1
-              coot_version_status=0
-          fi
-      fi
-    done
+    if [ "$coot_version_status" = "1" ] ; then
+       echo 'python and python+guile build differ => build again'
+       build_cycle=$(($build_cycle+1))
+       echo tried $build_cycle times so far
+       if [ "$build_cycle" = "3" ] ; then
+  		echo We tried 3 times to build consistent python and python+guile version
+  		echo BUT FAILED!!
+		echo exiting build!
+		build_installer=1
+        	coot_version_status=0
+       fi
+    fi
+   fi 
+  else
+    # coot python did not build ok! We try 3 more times
+    echo python build failed '=>' try again
+    minor_build_cycle=$(($minor_build_cycle+1))
+    echo tried $minor_build_cycle times so far
+    if [ "$minor_build_cycle" = "3" ] ; then
+      echo We tried 3 times to build python coot
+      echo BUT FAILED!!
+      echo exiting build!
+      build_installer=1
+      coot_version_status=0
+    fi
+  fi
+done
 else
  # this is for installer only
-    rm /z/make_installer_only
-    . ${HOME}/wincoot-installer-variables
-    coot_test_status=0
+ coot_test_status=0
+ rm /z/make_installer_only
+ . ${HOME}/wincoot-installer-variables
 fi
 
 # flag for makensis, i.e. overwrite binary dir when stable release
@@ -417,7 +359,7 @@ fi
 # not really working on msys right now
 #chmod 755 /z/build-logs/MINGW32_NT-6.1-sarabellum
 #chmod 744 /z/build-logs/MINGW32_NT-6.1-sarabellum/*
-#chmod 744 /z/software/binaries/pre-release/*
+#chmod 744 /z/software/binaries/nightlies/pre-release/*
 #chmod 744 /z/software/binaries/stable/*
 #chmod 755 /z/build-logs/MINGW32_NT-6.1-sarabellum/*
 #chmod 744 /z/build-logs/MINGW32_NT-6.1-sarabellum/*/*
