Add a test for working Python to build-it-3-3, exit on failure

diff --git a/build-it-3-3 b/build-it-3-3
--- a/build-it-3-3
+++ b/build-it-3-3
@@ -2891,6 +2891,20 @@ else
     echo not building python:
 fi
 
+############ test python, exit on failure ##################
+
+$install_top_dir/bin/python3 <<EOF
+import ctypes
+print(dir(ctypes))
+EOF
+if [ $? = 0 ] ; then
+   echo Good Python
+else
+   echo Python not working
+   exit 2
+fi
+
+
 ###############################################################################
 ##########         meson before gobject-introspection             #############
 ###############################################################################
