pycairo needs cairo 1.4.12 - so test for cairo, setting build_gtk=1 on failure.

diff --git a/build-it-gtk2 b/build-it-gtk2
--- a/build-it-gtk2
+++ b/build-it-gtk2
@@ -204,7 +204,9 @@
 # 3.04 20080128 Add a test for the existance of pygtk
 # 3.05 20080129 Add pkg-config and pygobject 
 # 3.06 20080130 Add test for pycairo
-script_version=3.06
+# 3.07 20080130 pycairo needs 1.4.12 - so test for cairo, setting build_gtk=1 on 
+#               failure
+script_version=3.07
 
 
 # :: NOTE:: 
@@ -1176,9 +1178,14 @@ build_gtk=
 pkg-config --atleast-version=2.8 gtk+-2.0
 gtk_pkg_config_status=$?
 if [ "$gtk_pkg_config_status" = 0 ] ; then 
-   # have gtk
-   echo :::::::: gtk is up to date
-   build_gtk=
+   if pkg-config --atleast-version=1.4.12 cairo ; then
+      # have gtk
+      echo :::::::: gtk is up to date, cairo is up to date
+      build_gtk=
+   else
+      echo cairo is not not up to date, rebuild gtk and friends
+      build_gtk=1
+   fi
 else 
    # no recent/good gtk
    echo :::::::: gtk and dependencies need to be built
@@ -1806,6 +1813,7 @@ if test -n "$build_gtk" ; then
    glitz_status=$?
    if [ "$glitz_status" != 0 ] ; then
       echo make of glitz failed
+      gtk_set_failure="make of glitz failed"
    else
       $MAKE install
    fi
@@ -1822,6 +1830,7 @@ if test -n "$build_gtk" ; then
       glib_status=$?
       if [ "$glib_status" != 0 ] ; then
          echo make of glib failed
+         gtk_set_failure="make of glib failed"
       else
          $MAKE install
       fi
@@ -1839,6 +1848,7 @@ if test -n "$build_gtk" ; then
       librsvg_status=$?
       if [ "$librsvg_status" != 0 ] ; then
          echo make of librsvg failed
+         gtk_set_failure="make of librsvg failed"
       else
          $MAKE install
       fi
@@ -1855,6 +1865,7 @@ if test -n "$build_gtk" ; then
       $MAKE
       cairo_status=$?
       if [ "$cairo_status" != 0 ] ; then
+         gtk_set_failure="make of cairo failed"
          echo make of cairo failed
       else
          $MAKE install
@@ -1873,6 +1884,7 @@ if test -n "$build_gtk" ; then
       pango_status=$?
       if [ "$pango_status" != 0 ] ; then
          echo make of pango failed
+         gtk_set_failure="make of pango failed"
       else
          $MAKE install
       fi
@@ -1891,13 +1903,19 @@ if test -n "$build_gtk" ; then
       gtk2_status=$?
       if [ "$gtk2_status" != 0 ] ; then
          echo make of gtk+2 failed
+         gtk_set_failure="make of gtk+2 failed"
       else
          $MAKE install
       fi
       cd - 
    fi
-
+   if test -n "$gtk_set_failure" ; 
+      exit 1
+   fi
    ) > $HOSTLOGDIR/06-gtk-prerequisites.txt 2>&1
+   if $? != 0 ; then
+      echo gtk set failed somewhere
+   fi
 fi
 
 
