fix disconnected added atoms bugs (and modify add terminal residue test to     test for this; python only) add python modules for binary update (not fully tested, needs more...) update windows build-it add get_torsion_py

diff --git a/build-it-win b/build-it-win
--- a/build-it-win
+++ b/build-it-win
@@ -333,11 +333,11 @@ fallback_coot_version=coot-0.5.2
 #   End of tinkering with parameters.
 # ----------------------------------------------------------------
 
-# First, check that this is bash!
+# First, check that this is bash.
 # 
 if [ "$BASH" = "" ] ; then 
-   echo this is not bash\!
-   echo this must be run with bash\!
+   echo this shell is not bash\!
+   echo this script must be run with bash\!
    exit
 fi
 
@@ -407,7 +407,6 @@ function make_tar {
     cd $install_top_dir/..
     if [ -e $tar_dir ] ; then
        echo taring nightly... from $tar_dir to $tar_file_name
-       echo taring nightly... from $tar_dir to $tar_file_name >&2
        tar czf $tar_file_name $tar_dir
        status=$?
        if [ "$status" != 0 ] ; then 
@@ -421,7 +420,6 @@ function make_tar {
        fi
     else
        echo ERROR:: tar target directory $tar_dir does not exist.
-       echo ERROR:: tar target directory $tar_dir does not exist. >&2
     fi
 }
 
@@ -448,6 +446,10 @@ function setup_ccp4 {
 # exit
 function my_exit {
 
+   exit_arg=$1
+   shift
+   extra_args=$*
+
    # remove evtl. existing coot-version files
    # and installer variable file
    rm -f $install_top_dir/coot-version
@@ -464,7 +466,7 @@ function my_exit {
    echo build_coot_prerelease=$build_coot_prerelease   >> $var_file
    echo coot_build_status=$coot_build_status >> $var_file
 
-   echo fail-build > $LOGS/gtk2${build_type}-test-status
+   echo fail-build $extra_args > $LOGS/gtk2${build_type}-test-status
    if [ -e $LOGS/gtk2${build_type}-build-status ] ; then
       rm $LOGS/gtk2${build_type}-build-status
    fi
@@ -473,7 +475,7 @@ function my_exit {
    cp -r ${LOGS} ${PUBLIC_HTML_LOGS}
    echo copy the log files from ${LOGS} to ${PUBLIC_HTML_LOGS}
 
-   exit $1
+   exit $exit_arg
 }
 
 
@@ -793,6 +795,10 @@ if test $OS = OSF1 ; then
    systype=${osversion}-OSF1
 fi
 
+if test "$OS" = "MINGW32_NT-5.1" ; then
+   systype=`uname -m`
+fi
+
 echo systype: $systype
 
 echo update_libtool: $update_libtool
@@ -988,8 +994,11 @@ fi
 # latest version (without .tar.gz extension)
 coot_version=$fallback_coot_version
 
+pre_release_server_dir=http://www.ysbl.york.ac.uk/~emsley/software/pre-release/
+pre_release_server_dir=http://www.biop.ox.ac.uk/coot/software/source/pre-releases/
+
 ${WGET} -O ${AUTOBUILD_SOURCES}/index.html -o ${AUTOBUILD_SOURCES}/wget-e.s.p.log http://www.ysbl.york.ac.uk/~emsley/software/
-${WGET} -O ${AUTOBUILD_SOURCES}/index-pre-release.html -o ${AUTOBUILD_SOURCES}/wget-e.s.p.log http://www.ysbl.york.ac.uk/~emsley/software/pre-release/
+${WGET} -O ${AUTOBUILD_SOURCES}/index-pre-release.html -o ${AUTOBUILD_SOURCES}/wget-e.s.p.log $pre_release_server_dir
 pre_release_files_html=""
 if [ $build_coot_prerelease = 1 ]  ; then 
    pre_release_files_html=${AUTOBUILD_SOURCES}/index-pre-release.html
@@ -1088,7 +1097,7 @@ coot_prerelease_exists=
 
 if test "$build_coot_prerelease" = 1 ; then 
 
-   ${WGET} -O ${AUTOBUILD_SOURCES}/index.html -o ${AUTOBUILD_SOURCES}/wget-e.s.p.log http://www.ysbl.york.ac.uk/~emsley/software/pre-release
+   ${WGET} -O ${AUTOBUILD_SOURCES}/index.html -o ${AUTOBUILD_SOURCES}/wget-e.s.p.log $pre_release_server_dir
    coot_version_pre=`egrep href ${AUTOBUILD_SOURCES}/index.html | sed -e 's/.*">//' -e 's/<.*//' | awk ' /^coot-[0-9]\.[0-9]+.*-pre.*\.tar\.gz$/ { 
    last=$0 }
 END {
@@ -1107,7 +1116,7 @@ END {
       coot_prerelease_exists=1
       # tinker with coot_prefix, it is generic_prefix with pre-release added to prefix dir
       coot_prefix="--prefix=${AUTOBUILD_INSTALLED}-pre-release-gtk2${build_type} ${config_extras:-}"
-      coot_source_tar_file=http://www.ysbl.york.ac.uk/~emsley/software/pre-release/$coot_version_pre
+      coot_source_tar_file=$pre_release_server_dir/$coot_version_pre
       coot_version=`echo $coot_version_pre | sed s/\.tar.gz//`
       BINARY_TAR_DEST_DIR=$NIGHTLY_DEST_DIR
       mkdir -p ${NIGHTLY_DEST_DIR}
@@ -1269,6 +1278,10 @@ else
    my_exit 2
 fi
 
+# Hope this doesnt mess things on windows?!
+# clean up old test status:
+echo build-in-progress    > $LOGS/$build_type-build-status
+echo waiting for build... > $LOGS/$build_type-test-status
 
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -1866,9 +1879,8 @@ fi
 # libccp4c:
 if test -n "$build_ccp4c" ; then 
     echo BUILDING: libccp4c
-    echo BUILDING: libccp4c >&2
     ${WGET} http://www.ysbl.york.ac.uk/~emsley/software/extras/libccp4c-5.0.2-ysbl-2.tar.gz
-    # BL says:: not suer if needed?!
+    # BL says:: not sure if needed?!
     ${WGET} http://www.ysbl.york.ac.uk/~emsley/software/extras/ccp4-libs-underlay.tar.gz
     ${WGET} http://www.ysbl.york.ac.uk/~lohkamp/software/extras/ccp4_library_utils.c.patch
     ( 
@@ -1894,7 +1906,6 @@ fi
 #
 if test -n "$build_mmdb" ; then
    echo BUILDING mmdb:
-   echo BUILDING: mmdb >&2
 #
 # mmdb_version=1.0.10.  Not yet.
 # mmdb_version=1.0.8-ysbl-3
@@ -1988,7 +1999,7 @@ if test -n "$build_clipper" ; then
     #clipper_version=20ac
     #clipper_version=2.1-081201-ac
     #clipper_version=2.1-090210-ac
-    clipper_version=2.1-090520-ac
+    clipper_version=2.1-090522-ac
     clipper_dir_version=2.1
     ${WGET} http://www.ysbl.york.ac.uk/~cowtan/clipper/clipper-$clipper_version.tar.gz
     if [ "$need_clipper_contrib_patch" = true ] ; then
@@ -2656,6 +2667,8 @@ if test -n "$build_guile" ; then
     echo BUILDING guile:
 #
 guile_version=1.8.3
+#guile_version=1.8.6
+# dont think works yet!?
 ${WGET} http://www.mirrorservice.org/sites/ftp.gnu.org/gnu/guile/guile-${guile_version}.tar.gz
 
 cd $build_dir
@@ -2857,7 +2870,7 @@ if test -n "$build_gsl" ; then
 #
 gsl_version=1.8
 # not yet
-# gsl_version=1.11
+# gsl_version=1.12
 ${WGET} http://downloads.sourceforge.net/gnuwin32/gsl-$gsl_version-bin.zip
 ${WGET} http://downloads.sourceforge.net/gnuwin32/gsl-$gsl_version-lib.zip
 ${WGET} http://www.ysbl.york.ac.uk/~lohkamp/software/extras/gsl-config
@@ -2887,7 +2900,6 @@ fi
 
 
 echo BUILDING coot: version $coot_version, python=$ENABLE_PYTHON_COOT guile=$ENABLE_GUILE_COOT
-echo BUILDING coot: version $coot_version, python=$ENABLE_PYTHON_COOT guile=$ENABLE_GUILE_COOT>&2
 if [ "$build_coot_prerelease" != 1 ] ; then 
    # normal release coot
    ${WGET} http://www.ysbl.york.ac.uk/~emsley/software/$coot_version.tar.gz 
@@ -2901,6 +2913,7 @@ else
       # compile release code then:
       ${WGET} http://www.ysbl.york.ac.uk/~emsley/software/$coot_version.tar.gz 
    fi 
+   coot_revision=`echo $coot_version | awk '{a=$1; i=index(a,"revision"); print substr(a,i)}'`
    # ${WGET} http://www.ysbl.york.ac.uk/~emsley/software/coot-static.patch
 fi
 
@@ -2914,7 +2927,7 @@ if [ -e ${AUTOBUILD_SOURCES}/$coot_version.tar.gz ] ; then
 else 
    echo badness ${AUTOBUILD_SOURCES}/$coot_version.tar.gz does not exist.
    echo nothing left to do then.  Goodbye.
-   exit 2
+   my_exit 2 $coot_version.tar.gz not found
 fi
 # we have to go to build dir
 cd $build_dir
@@ -2978,7 +2991,6 @@ fi
 ###############################################################################
 #
 echo BUILDING coot: version $coot_version, python=$ENABLE_PYTHON_COOT guile=$ENABLE_GUILE_COOT
-echo BUILDING coot: version $coot_version, python=$ENABLE_PYTHON_COOT guile=$ENABLE_GUILE_COOT>&2
 
 # set the python tag outside the compile/install sub-shell.
 if [ "$ENABLE_PYTHON_COOT" = "no" ] ; then 
@@ -3086,20 +3098,17 @@ fi
 coot_build_status=$?
 if [ $coot_build_status != 0 ] ; then
     echo coot build failed, exiting.
-    echo coot build failed, exiting. >&2
-    echo fail-build > $LOGS/gtk2${build_type}-build-status
-    my_exit 2
+    echo fail-build $coot_revision > $LOGS/gtk2${build_type}-build-status
+    my_exit 2 $coot_revision
 else 
     # and finally write a coot-version file for the installer
     wincoot_version=${coot_version/coot-}
     echo '!define WinCootVersion "'${wincoot_version}'"' >$install_top_dir/coot-version
 
     echo coot build was good.
-    echo coot build was good. >&2
-    echo pass-build > $LOGS/gtk2${build_type}-build-status
+    echo pass-build $coot_revsion > $LOGS/gtk2${build_type}-build-status
 fi
 echo done coot build. 
-echo done coot build. >&2
 
 
 # now, do we need to add the extra data files, the refmac monomer
@@ -3189,6 +3198,11 @@ echo copy the log files from ${LOGS} to ${PUBLIC_HTML_LOGS}
 # either change once manually or
 # run in masta unix script
 
+# we set the binary type here and pass it to the installer script
+# only if that works it shoudl be copied and updated on the website. 
+binary_type_latest=type-binary-${OS}-${systype}${python_tag}${gtk2}-latest.txt
+
+
 # we write a number of variables to a file which we import in the
 # masta script so that we preserve these
 # first remove an the old file
@@ -3196,10 +3210,11 @@ var_file=${HOME}/wincoot-installer-variables
 echo deleting $var_file
 rm -f $var_file
 echo LOGS=${LOGS}                          > $var_file
-echo NIGHTLY_DEST_DIR=${NIGHTLY_DEST_DIR} >> $var_file
-echo wincoot_version=$wincoot_version     >> $var_file
+echo NIGHTLY_DEST_DIR=${NIGHTLY_DEST_DIR}   >> $var_file
+echo wincoot_version=$wincoot_version       >> $var_file
 echo build_coot_prerelease=$build_coot_prerelease >> $var_file
-echo coot_build_status=$coot_build_status >> $var_file
-echo coot_test_status=$coot_test_status   >> $var_file
+echo coot_build_status=$coot_build_status   >> $var_file
+echo coot_test_status=$coot_test_status     >> $var_file
+echo binary_type_latest=$binary_type_latest >> $var_file
 
 echo finished.
