Make the downloader functions more robust

diff --git a/lhasa/get_sources b/lhasa/get_sources
--- a/lhasa/get_sources
+++ b/lhasa/get_sources
@@ -35,14 +35,14 @@ getrdkit() {
         echo "Using existing rdkit"
     else
         echo "Downloading RDKit source"
-        curl -L https://github.com/rdkit/rdkit/archive/refs/tags/$rdkit_release.tar.gz -o "$rdkit_release.tar.gz"
+        curl -fL https://github.com/rdkit/rdkit/archive/refs/tags/$rdkit_release.tar.gz -o "$rdkit_release.tar.gz" || fail "Failed to download RDKit source"
         echo
         echo "Unpacking RDKit source"
-        tar xf "$rdkit_release.tar.gz"
+        tar xf "$rdkit_release.tar.gz" || fail "Failed to unpack RDKit source"
         echo
         echo "Getting git version of rapidjson for RDKit"
         cd rdkit-$rdkit_release/External &&\
-        git clone https://github.com/Tencent/rapidjson.git rapidjson-1.1.0
+        git clone https://github.com/Tencent/rapidjson.git rapidjson-1.1.0 || fail "Failed to clone rapidjson"
     fi
     echo
 }
@@ -53,10 +53,10 @@ getgraphene() {
         echo "Using existing graphene"
     else
         echo "Downloading graphene source"
-        curl -L https://github.com/ebassi/graphene/archive/refs/tags/$graphene_release.tar.gz -o graphene_$graphene_release.tar.gz
+        curl -fL https://github.com/ebassi/graphene/archive/refs/tags/$graphene_release.tar.gz -o graphene_$graphene_release.tar.gz || fail "Failed to download graphene source"
         echo
         echo "Unpacking graphene source"
-        tar xf "graphene_$graphene_release.tar.gz"
+        tar xf "graphene_$graphene_release.tar.gz" || fail "Failed to unpack graphene source"
     fi
     echo
 }
@@ -68,10 +68,10 @@ getsigcpp() {
         echo "Using existing libsigcplusplus"
     else
         echo "Downloading libsigc++ source"
-        curl -L https://github.com/libsigcplusplus/libsigcplusplus/archive/refs/tags/$libsigcpp_release.tar.gz -o libsigcplusplus_$libsigcpp_release.tar.gz
+        curl -fL https://github.com/libsigcplusplus/libsigcplusplus/archive/refs/tags/$libsigcpp_release.tar.gz -o libsigcplusplus_$libsigcpp_release.tar.gz || fail "Failed to download libsigc++ source"
         echo
         echo "Unpacking libsigc++ source"
-        tar xf "libsigcplusplus_$libsigcpp_release.tar.gz"
+        tar xf "libsigcplusplus_$libsigcpp_release.tar.gz" || fail "Failed to unpack libsigc++ source"
     fi
     echo
 }
@@ -82,8 +82,8 @@ getboost() {
         echo "Using existing boost"
     else
         echo "Checking out boost"
-        curl -L https://github.com/boostorg/boost/releases/download/boost-$boost_release/boost-$boost_release-cmake.tar.gz -o boost_$boost_release.tar.gz
-        tar xf boost_$boost_release.tar.gz
+        curl -fL https://github.com/boostorg/boost/releases/download/boost-$boost_release/boost-$boost_release-cmake.tar.gz -o boost_$boost_release.tar.gz || fail "Failed to download boost source"
+        tar xf boost_$boost_release.tar.gz || fail "Failed to unpack boost source"
     fi
     echo
 }
